name: Add to Exchange and Deploy to Sandbox

on:
  push:
    tags:
      - 'production_blue_[0-9][0-9][0-9][0-9][0-9][0-9][0-9][0-9]_[0-9][0-9]'

env:
  APPID: ${{ secrets.mule_connected_app_sand_id }}
  APPSECRET: ${{ secrets.mule_connected_app_sand_secret }}
  ENVID: ${{ secrets.sandbox_client_id }}
  ENVSECRET: ${{ secrets.sandbox_client_secret }}

jobs:
  build-to-exchange:
    runs-on: ubuntu-22.04
    steps:
    - name: Checkout this repo
      uses: actions/checkout@v4.2.2
    - name: Setup Java
      uses: actions/setup-java@v4.7.1
      with:
        distribution: 'temurin'
        java-version: '17.0.12'
    - name: Add JAVA_HOME/bin to PATH
      run: echo "$JAVA_HOME/bin" >> $GITHUB_PATH
    - name: Setup Maven
      uses: s4u/setup-maven-action@v1.18.0
      with:
        maven-version: 3.9.6
    - name: Show Ubuntu version
      run: cat /etc/os-release
    - name: Show Java version
      run: java -version
    - name: Show Maven version
      run: mvn -version
    - name: maven-settings-xml-action
      uses: whelk-io/maven-settings-xml-action@v22
      with:
        repositories: '[{ "id": "anypoint-exchange-v3", "url": "https://maven.anypoint.mulesoft.com/api/v3/maven" }]'
        servers: '[{ "id": "anypoint-exchange-v3", "username": "~~~Client~~~", "password": "${env.APPID}~?~${env.APPSECRET}" }]'
    - name: Deploy to Exchange
      working-directory: ./contract-api
      run: |
        artifactName=$(ls *.jar | head -1)
        mvn clean deploy -e -DskipMunitTests 

  deploy:
    needs: build-to-exchange
    runs-on: ubuntu-latest
    steps:
    - name: Show Ubuntu version
      run: cat /etc/os-release
    - name: Show Java version
      run: java -version
    - name: Show Maven version
      run: mvn -version
    - name: Checkout this repo
      uses: actions/checkout@v4.2.2
    - name: Deploy to Sandbox
      working-directory: ./contract-api
      run: |
        mvn clean deploy -e -DmuleDeploy -DskipMunitTests \
         -Dapp.name="contract-api" \
         -Denvironment="Sandbox" \
         -Dtarget.env="dev" \
         -Danypoint.psname="Cloudhub-US-East-2"  \
         -Dconnected.app.id="$APPID" \
         -Dconnected.app.secret="$APPSECRET" \
         -Denv.client.id="$ENVID" \
         -Denv.client.secret="$ENVSECRET"

